# ComfyUI/custom_nodes/ComfyUI_JANodes/__init__.py

from .Lora2StackToString import NODE_CLASS_MAPPINGS as NODE1_MAPPINGS
from .LoraStringSplitter import NODE_CLASS_MAPPINGS as NODE2_MAPPINGS
from .StringLoraLoaderModelOnly import NODE_CLASS_MAPPINGS as NODE3_MAPPINGS
from .StringLoraLoader import NODE_CLASS_MAPPINGS as NODE4_MAPPINGS

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(NODE1_MAPPINGS)
NODE_CLASS_MAPPINGS.update(NODE2_MAPPINGS)
NODE_CLASS_MAPPINGS.update(NODE3_MAPPINGS)
NODE_CLASS_MAPPINGS.update(NODE4_MAPPINGS)

from .Lora2StackToString import NODE_DISPLAY_NAME_MAPPINGS as NODE1_NAMES
from .LoraStringSplitter import NODE_DISPLAY_NAME_MAPPINGS as NODE2_NAMES
from .StringLoraLoaderModelOnly import NODE_DISPLAY_NAME_MAPPINGS as NODE3_NAMES
from .StringLoraLoader import NODE_DISPLAY_NAME_MAPPINGS as NODE4_NAMES

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(NODE1_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(NODE2_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(NODE3_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(NODE4_NAMES)




